# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Especifica la rama que desencadenará el pipeline

pool:
  vmImage: 'ubuntu-latest'  # Imagen de la máquina virtual para ejecutar el pipeline

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Versión de Node.js a utilizar
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build'  # Ruta al directorio de archivos a comprimir
    includeRootFolder: false
    archiveType: 'zip'  # Tipo de archivo a crear (puedes ajustarlo según tus necesidades)
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'  # Ruta donde se almacenará el archivo comprimido
    replaceExistingArchive: true
  displayName: 'Archive build files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'  # Ruta del archivo comprimido a publicar
    ArtifactName: 'drop'  # Nombre del artefacto
    publishLocation: 'Container'  # Ubicación donde se publicarán los artefactos
  displayName: 'Publish build artifacts'
