# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: local

variables:
- group: project-vars

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
- script: |
    npm run build
  displayName: 'npm build react'

- script: |
    npm install -g @azure/static-web-apps-cli
  displayName: Installing SWA CLI

- task: AzureCLI@2
  displayName: Deploying app to AZ Static Web App
  inputs:
    azureSubscription: SubMafer
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      swa deploy --app-name VehicleInvWeb --env production
  env:
    SWA_CLI_DEPLOYMENT_TOKEN: $(staticwebappkey)